version: 0.2

phases:
  install:
    commands:
      - apt-get install -y make gcc
      - gem install jekyll
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - jekyll build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - _site/**/*